export default {
  sidebar: {
    Wave: {
      width: ["100%", "960px"],
      marginTop: "40px",
      marginLeft: 0,
      marginBottom: "40px",
      position: "relative",
      display: ["block", "flex"],
      flexDirection: ["", "row-reverse"],
    },
    ScrollerContainer: {
      flex: [1, "500px"],
      paddingLeft: 0,
      marginRight: [0, "40px"],
      paddingTop: ["50px", 0],
    },
    ScrollerStep: {
      position: "relative",
      padding: 0,
      minHeight: "250px",
      display: "flex",
      alignItems: "center",
      borderLeft: "none",
      width: ["auto", "388px"],
    },
    ScrollerProgress: {
      position: "absolute",
      left: "-12px",
      backgroundColor: "secondary",
    },
    StickerContainer: {
      width: ["100vw", "40%"],
      marginLeft: ["calc(50% - 50vw)", "40px"],
      position: ["sticky", "static"],
      top: [0, "auto"],
      zIndex: [1, "auto"],
      height: ["50vh", "auto"],
      backgroundColor: "negativeBackground",
      color: "negativeText",
    },
    Sticker: {
      position: ["static", "sticky"],
      width: "100%",
      height: ["100%", "40vh"],
      top: ["auto", "30vh"],
      border: ["none", "none"],
    },
    focus: [0.7, 0.5],
  },
}
